// 保存佛事的参数
const saveFoShiParams = {
  // 与接口返回的字段一致
  isAutoFinish: 0,
  subdivideStr: [
    {
      postScript: [
        {
          id: 625473,
          inputType: 12,
          prompt_text: '请填写功德主姓名',
          name: '功德芳名',
          is_must: 0,
          dataType: 0,
          pic_num: 0,
          describe: '',
          isVerify: 0,
          font_length: 10,
        },
        {
          id: 625474,
          inputType: 5,
          prompt_text: '请填写联系人电话（方便寺院与您联系）',
          name: '联系电话',
          is_must: 0,
          dataType: 0,
          pic_num: 0,
          describe: '',
          isVerify: 0,
          font_length: 0,
        },
        {
          id: 625475,
          inputType: 15,
          prompt_text: '请填写您的心愿',
          name: '心愿',
          is_must: 0,
          dataType: 0,
          pic_num: 0,
          describe: '',
          isVerify: 0,
          font_length: 0,
        },
      ],
      name: '佛前供斋',
      printer: [
        {
          qrcodePrint: 3,
          printerId: 1,
          continuousPrintNum: 1,
          isPrintMobile: 1,
          sealType: 2,
          sealTypeBottom: 3,
          fontType: 0,
        },
      ],
      pic: 'https://pic.zizaihome.com/59b8822c-1673-4230-a922-29642031a86d.jpg',
      explain: '',
      isAutoFinish: 0,
      subdivide_type: 1,
      endTime: '2099-01-01 00:00:00',
      durationDay: 0,
      enroll_num: 0,
      sort: 0,
      id: 43302,
      price: '500',
      stock: -1,
    },
  ],
  title: '小程序',
  ceremonyTypeId: '14',
  pics: ['https://pic.zizaihome.com/c164ce97d1bec6ea8997fbb573ca5db0.jpg'],
  video: [],
  detail: '<p class="" style="">军事基地曾经的技术</p>',
  opName: '随喜功德',
  postScript: [],
  showClient: '1',
  showStatictics: 1,
  targetAmount: 0,
  startTime: '2021-04-22 16:07:55',
  endTime: '2099-12-31 23:55:00',
  showEndTime: '0',
  payDetail:
    '<section><section style="margin: 10px auto;"><section style="border-style: solid;-webkit-border-image: url(http://mpt.135editor.com/mmbiz_png/yqVAqoZvDibGpfYS2cC4YzbozH31oekibOFPBxA1CDIwaGogibNAnYBrrLIvt9q2U2RhpJruHxyI9YyMStIK84ibgw/0?wx_fmt=png) 65 fill;border-width: 20px;padding: 5px;color:#feda8c;"><p style="text-align: center;"><span style="font-size: 24px; caret-color: red;"><br/></span></p><p style="text-align: center;"><span style="font-size: 24px; caret-color: red;">随喜赞叹，功德无量。</span></p><p style="text-align: center;"><span style="font-size: 24px; caret-color: red;">福慧双增，所愿皆遂。</span></p><p><span style="font-size: 24px; caret-color: red;"><br/></span></p></section></section></section>',
  explain: '',
  feedbackType: 1,
  allow_showVistNum: 1,
  custom_introduce: '',
  pay_succ_details_flag: 1,
  id: '10847',
  // 状态（0 进行中，1 未开始，2 草稿，-1 删除）
  op_status: 0,
};
