export default {
  msg: '获取成功',
  data: {
    tmplTitle: '供养三宝',
    showEndTime: '0',
    title: '供养三宝',
    showStatictics: '1',
    price: [5, 5.55, 5.88],
    showClient: 0,
    pics: [
      'http://imgs.zizaihome.com/1493178206680.jpg',
      'http://imgs.zizaihome.com/1493178201940.jpg',
    ],
    postScript: [
      {
        name: '功德芳名',
        pic_num: 0,
        dataType: 2,
        describe: '',
        font_length: 0,
        prompt_text: '请填写功德主姓名',
        isVerify: 0,
        inputType: 12,
        is_must: 1,
      },
      {
        name: '心愿',
        pic_num: 0,
        dataType: 2,
        describe: '',
        font_length: 200,
        prompt_text: '请填写您的心愿',
        isVerify: 0,
        inputType: 15,
        is_must: 1,
      },
      {
        name: '联系人',
        pic_num: 0,
        dataType: 2,
        describe: '',
        font_length: 0,
        prompt_text: '请填写联系人姓名（方便寺院与您联系）',
        isVerify: 0,
        inputType: 4,
        is_must: 1,
      },
      {
        name: '手机号码',
        pic_num: 0,
        dataType: 2,
        describe: '',
        font_length: 0,
        prompt_text: '请填写联系人电话（方便寺院与您联系）',
        isVerify: 0,
        inputType: 5,
        is_must: 1,
      },
    ],
    isAutoFinish: true,
    details: '<p>123</p>',
    opName: '随喜供养三宝',
    tmplCover:
      'https://pic.zizaihome.com/e24a7be9-e23c-4170-8280-e38161da6de2.jpg',
    pay_succ_details: '<p>456</p>',
    subdivideStr: [],
    stock: -1,
  },
  result: 0,
};
