export default {
  msg: '获取成功',
  data: {
    isEnd: 0,
    allow_showVistNum: 1,
    id: 4150,
    title: '本焕寺第二十期施放千台焰口及供灯法会（农历六月在线登记）',
    explain: '',
    detail: '',
    opName: '我要供灯、写牌位',
    pay_succ_details_flag: 0,
    stock: -1,
    status: 0,
    showEndTime: 0,
    showClient: 1,
    price: '',
    startTime: '',
    feedbackType: 1,
    ceremonyTypeId: 51,
    custom_introduce: '',
    isPrintMobile: 0,
    showStatictics: 0,
    pics: [
      'https://pic.zizaihome.com/603d8084-f68d-11e6-accd-00163e0c001e.jpg',
      'https://pic.zizaihome.com/53879d70-f68d-11e6-accd-00163e0c001e.jpg',
      'https://pic.zizaihome.com/50e866ee-f68d-11e6-accd-00163e0c001e.jpg',
      'https://pic.zizaihome.com/adef7372-c7ad-11e7-9bcf-00163e0c001e.jpg',
      'https://pic.zizaihome.com/277b738e-c116-11e6-82a5-00163e0c001e.jpg',
    ],
    isAutoFinish: 0,
    endTime: '',
    payDetail: '',
    subdivideStr: [
      {
        sort: 0,
        printer: [
          {
            continuousPrintNum: 1,
            printerId: 4,
            qrcodePrint: 1,
            isPrintMobile: 1,
          },
        ],
        name: '供灯',
        subdivide_type: null,
        price: 1000,
        pic:
          'https://pic.zizaihome.com/c01ea274-f716-11e6-accd-00163e0c001e.jpg',
        id: 11777,
        postScript: [
          {
            name: '祈福人姓名',
            pic_num: 0,
            dataType: 0,
            describe: null,
            font_length: 0,
            prompt_text: '例如：某某某合家',
            id: 183557,
            is_must: 1,
            inputType: 1,
            isVerify: 0,
          },
          {
            name: '联系电话',
            pic_num: 0,
            dataType: 0,
            describe: null,
            font_length: 0,
            prompt_text: '例如：180xxxxxxxx',
            id: 183558,
            is_must: 0,
            inputType: 5,
            isVerify: 0,
          },
          {
            name: '联系人',
            pic_num: 3,
            dataType: 2,
            describe: null,
            font_length: 0,
            prompt_text: '例如：某某某',
            id: 183559,
            is_must: 1,
            inputType: 4,
            isVerify: 0,
          },
          {
            name: '邮寄地址（邮费自付）',
            pic_num: 0,
            dataType: 2,
            describe: null,
            font_length: 0,
            prompt_text: '可选填（需要则填，不需要则不填）',
            id: 183560,
            is_must: 0,
            inputType: 6,
            isVerify: 0,
          },
          {
            name: '心愿',
            pic_num: 0,
            dataType: 2,
            describe: null,
            font_length: 0,
            prompt_text: '可选填一个心愿（需要则填，不需要则不填）',
            id: 183561,
            is_must: 0,
            inputType: 1,
            isVerify: 0,
          },
        ],
        isAutoFinish: null,
        enroll_num: 0,
        endTime: '2018-08-02 17:00:26',
        explain: null,
        stock: 93,
      },
      {
        sort: 1,
        printer: [
          {
            continuousPrintNum: 1,
            printerId: 4,
            qrcodePrint: 1,
            isPrintMobile: 1,
          },
        ],
        name: '祈福随喜小牌位',
        subdivide_type: null,
        price: 200,
        pic:
          'https://pic.zizaihome.com/3594c090-c122-11e6-82a5-00163e0c001e.jpg',
        id: 11778,
        postScript: [
          {
            name: '功德名字（最多5个）',
            pic_num: 0,
            dataType: 0,
            describe: null,
            font_length: 0,
            prompt_text: '例如：某某某、某某某……',
            id: 183562,
            is_must: 1,
            inputType: 1,
            isVerify: 0,
          },
          {
            name: '联系人',
            pic_num: 0,
            dataType: 0,
            describe: null,
            font_length: 0,
            prompt_text: '可选填',
            id: 183563,
            is_must: 0,
            inputType: 1,
            isVerify: 0,
          },
          {
            name: '联系电话',
            pic_num: 0,
            dataType: 0,
            describe: null,
            font_length: 0,
            prompt_text: '可选填',
            id: 183564,
            is_must: 0,
            inputType: 5,
            isVerify: 0,
          },
          {
            name: '邮寄地址（邮费自付）',
            pic_num: 0,
            dataType: 2,
            describe: null,
            font_length: 0,
            prompt_text: '可选填（需要则填，不需要则不填）',
            id: 183565,
            is_must: 0,
            inputType: 6,
            isVerify: 0,
          },
        ],
        isAutoFinish: null,
        enroll_num: 0,
        endTime: '2018-08-02 17:00:26',
        explain: null,
        stock: 136,
      },
    ],
  },
  result: 0,
};
