var data = {
  ifHasSub: false,
  getListParams: {
    page: 0,
    pageSize: 25,
    typeId: -1,
    filterType: 0,
    searchText: '',
    orderByJoinNum: '',
    orderByCollectMoney: '',
  },
  getListRes: {},
  handleListData: {},
  getPrinterConfig: {},
  currentPrinterConfig: {},
  getPrinterListRes: {},
  getSubListRes: {},
  localPrtCfg: {},
  curBuddhistId: 0,
  buddhistScheduleListHandleData: {},
  isSubmit: 0,
  videoPlayer: '',
  curUploadJqXHR: '',
};
export default data;
