import juicer from 'juicer';
var appConfig = {
  environment: 0,
};
appConfig.template = appConfig.template || {};
appConfig.template.component = {};
appConfig.template.component.singleText = [
  '<div class="form-group" data-type="${item.type}">',
  '<label for="singleText" class="col-sm-3 control-label"><strong data-input="${item.input_id}">${item.name}</strong>',
  '{@if item.is_must==1 }',
  '<sup>*</sup>',
  '{@/if}',
  '</label>',
  '<div class="col-sm-9">',
  '{@if item.name=="真实姓名" }',
  '{@if item.is_must==1 }',
  '<input id="${item.input_id}" data-id="required" name="singleText" type="text" class="form-control"/>',
  '{@else}',
  '<input id="${item.input_id}" name="singleText" type="text" class="form-control"/>',
  '{@/if}',
  '<span class="cancel-icon" aria-hidden="true">&times;</span>',
  '<span class="tip_icon"></span>',
  '{@if item.is_must==1}',
  '<span data-id="require_msg" style="display:none;color:red"></span>',
  '{@/if}',
  '{@else if item.name=="毕业院校" }',
  '{@if item.is_must==1 }',
  '<input id="${item.input_id}" data-id="required" name="singleText" type="text" class="form-control"/>',
  '{@else}',
  '<input id="${item.input_id}" name="singleText" type="text" class="form-control"/>',
  '{@/if}',
  '<span class="icon cancel-icon img_icon graduatedSchool_icon " aria-hidden="true"></span>',
  '<span class="tip_icon"></span>',
  '{@if item.is_must==1}',
  '<span data-id="require_msg" style="display:none;color:red"></span>',
  '{@/if}',
  '{@else if item.name=="学习专业"}',
  '{@if item.is_must==1}',
  '<input id="${item.input_id}" data-id="required" name="singleText" type="text" class="form-control"/>',
  '{@else}',
  '<input id="${item.input_id}" name="singleText" type="text" class="form-control"/>',
  '{@/if}',
  '<span class="icon cancel-icon img_icon major_icon " aria-hidden="true"></span>',
  '<span class="tip_icon"></span>',
  '{@if item.is_must==1}',
  '<span data-id="require_msg" style="display:none;color:red"></span>',
  '{@/if}',
  '{@else if item.name=="工作单位" }',
  '{@if item.is_must==1}',
  '<input id="${item.input_id}" data-id="required" name="singleText" type="text" class="form-control"/>',
  '{@else}',
  '<input id="${item.input_id}" name="singleText" type="text" class="form-control"/>',
  '{@/if}',
  '<span class="icon cancel-icon img_icon employer_icon " aria-hidden="true"></span>',
  '<span class="tip_icon"></span>',
  '{@if item.is_must==1}',
  '<span data-id="require_msg" style="display:none;color:red"></span>',
  '{@/if}',
  '{@else if item.name=="职务"}',
  '{@if item.is_must==1}',
  '<input id="${item.input_id}" data-id="required" name="singleText" type="text" class="form-control"/>',
  '{@else}',
  '<input id="${item.input_id}" name="singleText" type="text" class="form-control"/>',
  '{@/if}',
  '<span class="icon cancel-icon img_icon occupation_icon " aria-hidden="true"></span>',
  '<span class="tip_icon"></span>',
  '{@if item.is_must==1}',
  '<span data-id="require_msg" style="display:none;color:red"></span>',
  '{@/if}',
  '{@else if item.name=="身份证号"}',
  '{@if item.is_must==1}',
  '<input id="${item.input_id}" data-id="required" name="singleText" type="text" class="form-control"/>',
  '{@else}',
  '<input id="${item.input_id}" name="singleText" type="text" class="form-control"/>',
  '{@/if}',
  '<span class="icon cancel-icon img_icon ID_icon " aria-hidden="true"></span>',
  '<span class="tip_icon"></span>',
  '{@if item.is_must==1}',
  '<span data-id="require_msg" style="display:none;color:red"></span>',
  '{@/if}',
  '{@else if item.name=="电子邮件"}',
  '{@if item.is_must==1}',
  '<input id="${item.input_id}" data-id="required" name="singleText" type="text" class="form-control"/>',
  '{@else}',
  '<input id="${item.input_id}" name="singleText" type="text" class="form-control"/>',
  '{@/if}',
  '<span class="icon cancel-icon img_icon email_icon " aria-hidden="true"></span>',
  '<span class="tip_icon"></span>',
  '{@if item.is_must==1}',
  '<span data-id="require_msg" style="display:none;color:red"></span>',
  '{@/if}',
  '{@else if item.name=="法名"}',
  '{@if item.is_must==1}',
  '<input id="${item.input_id}" data-id="required" name="singleText" type="text" class="form-control"/>',
  '{@else}',
  '<input id="${item.input_id}" name="singleText" type="text" class="form-control"/>',
  '{@/if}',
  '<span class="icon cancel-icon img_icon fahao_icon " aria-hidden="true"></span>',
  '<span class="tip_icon"></span>',
  '{@if item.is_must==1}',
  '<span data-id="require_msg" style="display:none;color:red"></span>',
  '{@/if}',
  '{@else if item.name=="可参与时间"}',
  '{@if item.is_must==1}',
  '<input id="${item.input_id}" data-id="required" name="singleText" type="text" class="form-control"/>',
  '{@else}',
  '<input id="${item.input_id}" name="singleText" type="text" class="form-control"/>',
  '{@/if}',
  '<span class="icon cancel-icon img_icon participateTime_icon " aria-hidden="true"></span>',
  '<span class="tip_icon"></span>',
  '{@if item.is_must==1}',
  '<span data-id="require_msg" style="display:none;color:red"></span>',
  '{@/if}',
  '{@else}',
  '{@if item.is_must==1}',
  '<input id="${item.input_id}" data-id="required" name="singleText" type="text" class="form-control"/>',
  '{@else}',
  '<input id="${item.input_id}" name="singleText" type="text" class="form-control"/>',
  '{@/if}',
  '<span class="cancel-icon" aria-hidden="true">&times;</span>',
  '<span class="tip_icon"></span>',
  '{@if item.is_must==1}',
  '<span data-id="require_msg" style="display:none;color:red"></span>',
  '{@/if}',
  '{@/if}',
  '</div>',
  '</div>',
].join(' ');
appConfig.template.component.multipleText = [
  '<div class="form-group" data-type="${item.type}">',
  '<label for="multipleText" class="control-label col-sm-3 "><strong data-input="${item.input_id}">${item.name}</strong>',
  '{@if item.is_must==1}',
  '<sup>*</sup>',
  '{@/if}',
  '</label>',
  '<div class="col-sm-9">',
  '{@if item.is_must==1}',
  '<textarea name="multipleText" data-id="required" class="form-control" id="${item.input_id}"></textarea>',
  '<span data-id="require_msg" style="display:none;color:red"></span>',
  '{@else}',
  '<textarea name="multipleText" class="form-control" id="${item.input_id}"></textarea>',
  '{@/if}',
  '</div>',
  '</div>',
].join(' ');
appConfig.template.component.radioButton = [
  '<div class="form-group radio" data-type="${item.type}">',
  '<span class="col-sm-3 control-label radioLabel"><strong id="${item.input_id}" data-input="${item.input_id}">${item.name}</strong>',
  '{@if item.is_must==1}',
  '<sup>*</sup>',
  '{@/if}',
  '</span>',
  '<div class="col-sm-9">',
  '{@each i in range(0,item.len)}',
  '<label class="checkRadio {@if i==0}checked{@/if}" for="${item.options[i]}">',
  '<input name="radioButton" value="${item.options[i]}" type="radio" checked/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;${item.options[i]}',
  '</label>',
  '{@/each}',
  '<span class="tip_icon"></span><span id="radioButton_msg" style="display: none;color:red"></span>',
  '</div>',
  '</div>',
].join(' ');
appConfig.template.component.checkBoxes = [
  '<div class="form-group" data-type="${item.type}">',
  '<span class="col-sm-3 control-label"><strong data-input="${item.input_id}">${item.name}</strong>',
  '{@if item.is_must==1}',
  '<sup>*</sup>',
  '{@/if}',
  '</span>',
  '<div class="col-sm-9">',
  '<label class="checkSex checked" for="male">',
  '<input name="checkBoxes" value="" type="checkbox" checked/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;男',
  '</label>',
  '<label class="checkSex" for="female">',
  '<input name="checkBoxes" value="" type="checkbox"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;女',
  '</label>',
  '<span class="tip_icon"></span>1<span id="checkBoxes_msg" style="display: none;color:red"></span>',
  '</div>',
  '</div>',
].join(' ');
appConfig.template.component.confirmButton = [
  '<div class="form-group confirm" data-type="${item.type}">',
  '<span class="col-sm-3 control-label"><strong data-input="${item.input_id}">${item.name}</strong>',
  '{@if item.is_must==1}',
  '<sup>*</sup>',
  '{@/if}',
  '</span>',
  '<div class="col-sm-9">',
  '{@if item.is_must==1}',
  '<input type="checkbox" name="agree" id="${item.input_id}" data-id="required" >',
  '{@else}',
  '<input type="checkbox" name="agree" id="${item.input_id}">',
  '{@/if}',
  '<span class="tip_icon"></span><span data-id="confirmButton_msg" style="display:none;color:red;position: absolute;top:6px;left: 60px;"></span>',
  '</div>',
  '</div>',
].join(' ');
appConfig.template.component.numberText = [
  '<div class="form-group" data-type="${item.type}">',
  '<label for="numberText" class="col-sm-3 control-label"><strong data-input="${item.input_id}">${item.name}</strong>',
  '{@if item.is_must==1}',
  '<sup>*</sup>',
  '{@/if}',
  '</label>',
  '<div class="col-sm-9">',
  '{@if item.is_must==1}',
  '<input id="${item.input_id}" data-id="required" name="numberText" type="number" class="form-control"/>',
  '{@else}',
  '<input id="${item.input_id}" name="numberText" type="number" class="form-control"/>',
  '{@/if}',
  '<span class="cancel-icon" aria-hidden="true">&times;</span>',
  '<span class="tip_icon"></span>',
  '{@if item.is_must==1}',
  '<span data-id="require_msg" style="display:none;color:red"></span>',
  '{@/if}',
  '</div>',
  '</div>',
].join(' ');
appConfig.template.component.phoneText = [
  '<div class="form-group" data-type="${item.type}">',
  '<label for="phoneText" class="col-sm-3 control-label"><strong data-input="${item.input_id}">${item.name}</strong>',
  '{@if item.is_must==1}',
  '<sup>*</sup>',
  '{@/if}',
  '</label>',
  '<div class="col-sm-9">',
  '{@if item.is_must==1}',
  '<input id="${item.input_id}" data-id="required" name="phoneText" type="number" class="form-control"/>',
  '{@else}',
  '<input id="${item.input_id}" name="phoneText" type="number" class="form-control"/>',
  '{@/if}',
  '<span class="icon cancel-icon img_icon tel_icon " aria-hidden="true"></span>',
  '<span class="tip_icon"></span><span data-id="phone_msg" style="display:none;color:red"></span>',
  '</div>',
  '</div>',
].join(' ');
appConfig.template.component.timeText = [
  '<div class="form-group" data-type="${item.type}">',
  '<label for="timeText" class="control-label col-sm-3"><strong data-input="${item.input_id}">${item.name}</strong>',
  '{@if item.is_must==1}',
  '<sup>*</sup>',
  '{@/if}',
  '</label>',
  '<div class="col-sm-9">',
  '{@if item.is_must==1}',
  '<input id="${item.input_id}" data-id="required" name="timeText" class="form_datetime form-control" type="text"/>',
  '{@else}',
  '<input id="${item.input_id}" name="timeText" class="form_datetime form-control" type="text"/>',
  '{@/if}',
  '<span class="icon cancel-icon img_icon birthday_icon "></span>',
  '<span class="tip_icon"></span><span data-id="time_msg" style="display:none;color:red"></span>',
  '</div>',
  '</div>',
].join(' ');
appConfig.template.component.dropDownMenu = [
  '<div class="form-group" data-type="${item.type}">',
  '<label for="dropDownMenu" class="control-label col-sm-3 "><strong data-input="${item.input_id}">${item.name}</strong>',
  '{@if item.is_must==1}',
  '<sup>*</sup>',
  '{@/if}',
  '</label>',
  '{@if item.is_must==1}',
  '<select name="dropDown" id="${item.input_id}" data-id="required" data-live-search="true" class="selectpicker" data-id="requireSelect">',
  '{@each i in range(0,item.len)}',
  '<option value="${item.options[i]}">${item.options[i]}</option>',
  '{@/each}',
  '</select>',
  '{@else}',
  '<select name="dropDown" id="${item.input_id}" data-live-search="true" class="selectpicker">',
  '{@each i in range(0,item.len)}',
  '<option value="${item.options[i]}">${item.options[i]}</option>',
  '{@/each}',
  '</select>',
  '{@/if}',
  '</div>',
].join(' ');
appConfig.template.component.labelText = [
  '<div class="form-group" data-type="${item.type}">',
  '<label for="${item.name}" class="control-label col-sm-3"><strong data-input="${item.input_id}">${item.name}</strong></label>',
  '<div class="col-sm-9">',
  '<input id="label${item.input_id}" data-label="${item.input_id}" class="form-control wrap_tags" type="text" placeholder="可手动输入，如有多项请以空格分隔"/>',
  '<span class="icon cancel-icon img_icon ceremony_icon "></span>',
  '<div class="chooseBox choose${item.input_id}">',
  '<ul class="" style="padding-left: 20px;">',
  '<li class="clearfix">',
  '<dl>',
  '<dt></dt>',
  '<dd>',
  '{@each i in range(0,item.len)}',
  '<span class="tagbtn gract">${item.options[i]}</span>&nbsp;',
  '{@/each}',
  '</dd>',
  '</dl>',
  '</li>',
  '</ul>',
  '</div>',
  '</div>',
  '</div>',
].join(' ');
appConfig.template.component.addressText = [
  '<div class="form-group" data-type="${item.type}">',
  '<label for="address" class="control-label col-sm-3 "><strong data-input="${item.input_id}">${item.name}</strong>',
  '{@if item.is_must==1}',
  '<sup>*</sup>',
  '{@/if}',
  '</label>',
  '<div class="col-sm-9" id="addressPan">',
  '{@if item.is_must=="1"}',
  '<input class="form-control" readonly id="address" type="text" data-id="required" data-toggle="city-picker" data-simple="true" placeholder="点击从下拉面板中选择省/市/区">',
  '{@else}',
  '<input class="form-control" readonly id="address" type="text" data-toggle="city-picker" data-simple="true" placeholder="点击从下拉面板中选择省/市/区">',
  '{@/if}',
  '</div>',
  '</div>',
  '<div class="form-group">',
  '<label for="addressDetails" class="control-label col-sm-3 "></label>',
  '<div class="col-sm-9">',
  '{@if item.is_must=="1"}',
  '<input id="addressDetails" name="address" data-id="required" type="text" class="form-control" placeholder="详细住址"/>',
  '{@else}',
  '<input id="addressDetails" name="address" type="text" class="form-control" placeholder="详细住址"/>',
  '{@/if}',
  '</div>',
  '</div>',
].join(' ');
appConfig.template.component.splitLine = [
  '<div class="form-group" data-type="${item.type}">',
  '</div>',
].join(' ');
appConfig.template.component.submitButton = [
  '<div class="form-group" style="text-align: center">',
  '<span class="btn btn-success backgroundGreen btn-width" id="submit">保&nbsp;存</span>',
  '</div>',
].join(' ');
export default appConfig;
